# Generated by Django 5.2.5 on 2025-10-07 17:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_alter_categoria_slug_alter_categoria_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo'),
        ),
    ]
